### ISSUE TITLE
Space will be encoded

### ISSUE THREAD

**Issue by taooceros** [lostping/Flow.Launcher.Plugin.Kitty#1]
![image](https://user-images.githubusercontent.com/45326534/150566942-825b741c-c7db-4284-8864-ed407426555e.png)

**Comment by taooceros** [comment]
btw, there's a duplicate default settings session.

**Comment by lostping** [comment]
I see. The space encoding in portable mode is a bit tricky with my current code.
Will look how to work around that.

> btw, there's a duplicate default settings session.

You can remove the duplicate entry by disabling the option to always add kitty executable to the results.
I don't belive this counts as a bug, but I guess an enhancement.
KiTTY or PuTTY always open the default session when starting without parameters, so it should be okay to remove entry (to start the default session by name) completely.

**Comment by taooceros** [comment]
Gotcha, thank you!

**Comment by lostping** [comment]
Fixed in [1d90fa6](https://github.com/lostping/Flow.Launcher.Plugin.Kitty/commit/1d90fa6d0b2bf7a83006e412a54920caddef421f)
