### ISSUE TITLE
No sessions available

### ISSUE THREAD

**Issue by wsw70** [lostping/Flow.Launcher.Plugin.Kitty#5]
(I am new to Flow so apologies if this is obvious)

I installed the kitty plugin and chose my kitty executable (installed by `scoop` to `C:\Users\me\scoop\apps\kitty\current\kitty.exe`, `current` is a link to the actual versioned directory)

When trying `kt` in Flow I get

![image](https://user-images.githubusercontent.com/1345886/161965954-acbece73-9801-4fdd-a281-51b1fff18688.png)

→ that is no sessions are suggested

OTOH, when starting the executable above by hand I get 

![image](https://user-images.githubusercontent.com/1345886/161966092-cb0661b2-7490-4e47-b9d2-739e05fcc992.png)

Is there a place where I should define the working directory? (or something else)

**Comment by lostping** [comment]
Hi!
It makes a difference what binary is installed. If it is the portable kitty binary the plugin can use the session folder that is automatically generated in the folder where the binary is located. 

If you install the default binary only the registry option will work.

**Comment by wsw70** [comment]
> Hi! It makes a difference what binary is installed. If it is the portable kitty binary the plugin can use the session folder that is automatically generated in the folder where the binary is located.
> 
> If you install the default binary only the registry option will work.

Thank you. If I understand you correctly this means that only the portable version will work with Flow (and provide sessions as hints)?

**Comment by lostping** [comment]
Not quite correct. The portable executable will allow to use the portable option, as well as the registry option.
You can use the normal executable, but AFAIK you then are limited to use the registry option in the kitty flow plugin
